name: Build dix with Nix

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Nix Package (${{ matrix.system }})
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 50
    strategy:
      fail-fast: false
      matrix:
        system:
          - x86_64-linux
          - aarch64-linux
          - aarch64-darwin
        include:
          - system: x86_64-linux
            runner: ubuntu-latest
          - system: aarch64-linux
            runner: ubuntu-24.04-arm
          - system: aarch64-darwin
            runner: macos-15

    steps:
      - uses: actions/checkout@v6.0.2

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v14

      - name: Build dix
        run: nix build .#packages.${{ matrix.system }}.dix -L --no-link
